name: CI
run-name: Hugo blog deployment
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v3

      - name: SSH and run commands
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.DEPLOY_SERVER }}
              username: ${{ secrets.DEPLOY_USERNAME }}
              password: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Hugp
        run: sudo snap install hugo

      - name: Build the website
        run: hugo

      - name: Deploy the website
        run: >-
          rsync -avx --delete --exclude '.ssh' public/ $DEPLOY_USERNAME@$DEPLOY_SERVER:./
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME}}
